TEMPERATURE = 1

ACCELERATION_X = 2
ACCELERATION_Y = 3
ACCELERATION_Z = 4

WHEEL_SPEED_FL = 5
WHEEL_SPEED_FR = 6
WHEEL_SPEED_BL = 7
WHEEL_SPEED_BR = 8

SUSPENSION_FL = 9
SUSPENSION_FR = 10
SUSPENSION_BL = 11
SUSPENSION_BR = 12

CURRENT_FUEL_LEVEL = 13
