# Generated by Django 2.2.11 on 2020-04-29 12:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AGSensorType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('processing_formula', models.IntegerField(default=0)),
                ('format', django.contrib.postgres.fields.jsonb.JSONField()),
                ('graph_type', models.CharField(choices=[('graph', 'Graph'), ('map', 'Map'), ('gauge', 'Gauge')], default='graph', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AGVenue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_code', models.CharField(choices=[('UNKNOWN_FORMAT', 'Unknown Format'), ('MISSING_COLUMN', 'Missing Column'), ('MISSING_FIELD_IN_RAW_READING', 'Missing Field In Raw Reading'), ('INVALID_COLUMN_NAME', 'Invalid Column Name'), ('INVALID_COLUMN_VALUE', 'Invalid Column Value'), ('INVALID_FIELD_IN_RAW_READING', 'Invalid Field In Raw Reading'), ('FORMULA_PROCESS_MEASUREMENT_ERROR', 'Error When Formula Processing Measurement'), ('EXTRANEOUS_KEY_VALUE_PAIR_IN_MEASUREMENT', 'Extraneous Key-Value Pair In Measurement'), ('NO_ACTIVE_EVENT', 'No active event'), ('OTHER_ERROR', 'Other Error')], default='OTHER_ERROR', max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('raw_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AGSensor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial', models.IntegerField(default=1, unique=True)),
                ('name', models.CharField(blank=True, max_length=1024)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ag_data.AGSensorType')),
            ],
        ),
        migrations.CreateModel(
            name='AGMeasurement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('event_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ag_data.AGEvent')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ag_data.AGSensor')),
            ],
        ),
        migrations.AddField(
            model_name='agevent',
            name='venue_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ag_data.AGVenue'),
        ),
        migrations.CreateModel(
            name='AGActiveEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ag_data.AGEvent')),
            ],
        ),
    ]
