# Generated by Django 2.2.11 on 2020-03-09 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ag_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGVenue',
            fields=[
                ('venue_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(blank=True, max_length=100)),
                ('venue_description', models.CharField(blank=True, max_length=100)),
                ('venue_latitude', models.FloatField()),
                ('venue_longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='agsensor',
            name='sensor_description',
        ),
        migrations.AddField(
            model_name='agevent',
            name='event_venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ag_data.AGVenue'),
        ),
    ]
