# Generated by Django 2.2.11 on 2020-04-17 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ag_data', '0002_agactiveevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('error_id', models.AutoField(primary_key=True, serialize=False)),
                ('error_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_description', models.CharField(max_length=100)),
                ('error_raw_data', models.CharField(max_length=500)),
            ],
        ),
    ]
