# Generated by Django 2.2.11 on 2020-04-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ag_data', '0004_auto_20200424_0000'),
        ('ag_data', '0004_agsensortype_graph_type'),
    ]

    operations = [
    ]
