# Generated by Django 2.2.6 on 2019-10-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulatedData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("owner", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField()),
                ("temperature", models.IntegerField()),
                ("acceleration_x", models.IntegerField()),
                ("acceleration_y", models.IntegerField()),
                ("acceleration_z", models.IntegerField()),
                ("wheel_speed_fr", models.IntegerField()),
                ("wheel_speed_fl", models.IntegerField()),
                ("wheel_speed_br", models.IntegerField()),
                ("wheel_speed_bl", models.IntegerField()),
                ("suspension_fr", models.IntegerField()),
                ("suspension_fl", models.IntegerField()),
                ("suspension_br", models.IntegerField()),
                ("suspension_bl", models.IntegerField()),
            ],
        )
    ]
