# Generated by Django 2.2.5 on 2019-10-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EngineTemperatureSensor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.IntegerField()),
                (
                    "timestamp",
                    models.DateTimeField(verbose_name="date measurement was taken"),
                ),
            ],
        )
    ]
