# Generated by Django 2.2.5 on 2019-10-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('acceleration_x', models.FloatField()),
                ('acceleration_y', models.FloatField()),
                ('acceleration_z', models.FloatField()),
                ('wheel_speed_fr', models.FloatField()),
                ('wheel_speed_fl', models.FloatField()),
                ('wheel_speed_br', models.FloatField()),
                ('wheel_speed_bl', models.FloatField()),
                ('suspension_fr', models.FloatField()),
                ('suspension_fl', models.FloatField()),
                ('suspension_br', models.FloatField()),
                ('suspension_bl', models.FloatField()),
                ('initial_fuel', models.FloatField()),
                ('fuel_decrease_rate', models.FloatField()),
                ('initial_oil', models.FloatField()),
                ('oil_decrease_rate', models.FloatField()),
            ],
        ),
    ]
