# Generated by Django 2.2.6 on 2019-10-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulateddata',
            name='acceleration_x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='acceleration_y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='acceleration_z',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='fuel_decrease_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='initial_fuel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='initial_oil',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='oil_decrease_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='suspension_bl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='suspension_br',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='suspension_fl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='suspension_fr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='wheel_speed_bl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='wheel_speed_br',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='wheel_speed_fl',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='simulateddata',
            name='wheel_speed_fr',
            field=models.FloatField(default=0),
        ),
    ]
