# Generated by Django 2.2.6 on 2019-11-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mercury",
            "0004_accelerationsensor_fuellevelsensor_suspensionsensor_temperaturesensor_wheelspeedsensor",  # noqa
        )
    ]

    operations = [
        migrations.CreateModel(
            name="EventCodeAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_code", models.CharField(max_length=8)),
                ("enabled", models.BooleanField()),
            ],
        )
    ]
