# Generated by Django 2.2.7 on 2019-11-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("mercury", "0005_eventcodeaccess")]

    operations = [migrations.DeleteModel(name="SimulatedData")]
