# Generated by Django 2.2.11 on 2020-03-09 13:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0008_auto_20200225_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGEvent',
            fields=[
                ('event_uuid', models.UUIDField(default=uuid.uuid4, editable=False,
                                                primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=40)),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AGMeasurement',
            fields=[
                ('measurement_uuid', models.UUIDField(default=uuid.uuid4,
                                                      editable=False, primary_key=True,
                                                      serialize=False)),
                ('measurement_timestamp', models.DateTimeField(default=django.utils.
                                                               timezone.now)),
                ('measurement_value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('measurement_event', models.ForeignKey(on_delete=django.db.models.
                                                        deletion.CASCADE,
                                                        to='mercury.AGEvent')),
            ],
        ),
        migrations.CreateModel(
            name='AGSensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_name', models.CharField(blank=True, max_length=1024)),
                ('sensor_description', models.CharField(blank=True, max_length=1024)),
                ('sensor_processing_formula', models.IntegerField(default=0)),
                ('sensor_format', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='agmeasurement',
            name='measurement_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='mercury.AGSensor'),
        ),
    ]
