# Generated by Django 2.2.11 on 2020-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0009_auto_20200309_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agsensor',
            name='sensor_description',
        ),
        migrations.AddField(
            model_name='agevent',
            name='event_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
