# Generated by Django 2.2.11 on 2020-03-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0010_auto_20200309_1634'),
        ('mercury', '0009_events_field_general_data_sensor'),
    ]

    operations = [
    ]
