# Generated by Django 2.2.11 on 2020-03-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0011_merge_20200314_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agmeasurement',
            name='measurement_event',
        ),
        migrations.RemoveField(
            model_name='agmeasurement',
            name='measurement_sensor',
        ),
        migrations.DeleteModel(
            name='AGEvent',
        ),
        migrations.DeleteModel(
            name='AGMeasurement',
        ),
        migrations.DeleteModel(
            name='AGSensor',
        ),
    ]
