# Generated by Django 2.2.10 on 2020-03-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercury", "0011_merge_20200314_0111"),
    ]

    operations = [
        migrations.CreateModel(
            name="GFConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gf_name", models.CharField(max_length=64)),
                ("gf_host", models.CharField(max_length=128)),
                ("gf_token", models.CharField(max_length=256)),
                ("gf_current", models.BooleanField(default=False)),
            ],
        ),
    ]
