# Generated by Django 2.2.6 on 2020-03-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0015_gfconfig_gf_db_grafana_name'),
        ('mercury', '0012_auto_20200320_1735'),
    ]

    operations = [
    ]
