# Generated by Django 2.2.11 on 2020-04-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercury', '0018_remove_gfconfig_gf_db_grafana_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccelerationSensor',
        ),
        migrations.DeleteModel(
            name='AGEvent',
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='field',
            name='sensor_id',
        ),
        migrations.DeleteModel(
            name='FuelLevelSensor',
        ),
        migrations.AlterUniqueTogether(
            name='general_data',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='general_data',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='general_data',
            name='field_id',
        ),
        migrations.RemoveField(
            model_name='general_data',
            name='sensor_id',
        ),
        migrations.DeleteModel(
            name='SuspensionSensor',
        ),
        migrations.DeleteModel(
            name='TemperatureSensor',
        ),
        migrations.DeleteModel(
            name='WheelSpeedSensor',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='General_data',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
