# Generated by Django 2.2.10 on 2020-04-20 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mercury", "0019_auto_20200420_0028"),
        ("mercury", "0019_auto_20200420_2013"),
    ]

    operations = []
