# Generated by Django 2.2.10 on 2020-05-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercury", "0020_auto_20200421_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfconfig",
            name="gf_token",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
