# Generated by Django 2.2.10 on 2020-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercury", "0021_auto_20200502_1312"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfconfig",
            name="gf_password",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="gfconfig",
            name="gf_username",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
