# Generated by Django 2.2.10 on 2020-05-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercury", "0022_auto_20200502_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfconfig",
            name="gf_name",
            field=models.CharField(default="", max_length=64),
        ),
    ]
