# Generated by Django 2.2.10 on 2020-05-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mercury", "0024_auto_20200502_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gfconfig",
            name="gf_name",
            field=models.CharField(max_length=64),
        ),
    ]
